# Header
menu:
  首页: /
  归档: /archives
  收藏集: https://collection.yukapril.com
rss: /atom.xml

# Content
excerpt_link: 阅读更多
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
# - tag
- tagcloud
# - archive

# Footer
links:
  名片: http://jingchen.li
  GitHub: https://github.com/yukapril
  Weibo: http://weibo.com/119880129
  yukaPriL下午茶时间: http://yukapril.lofter.com
beian: 京ICP备15045677号-1

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-120054388-1
baidu_analytics: 515a77345b51b4568446b02f666467d3
favicon: /favicon.ico
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: false # if you want use valine,please set this value is true
  appId:  # leancloud application app id
  appKey:  # leancloud application app key
  notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: false # valine verify code (true/false)
  pageSize: 10 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
