name: auto-publisher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: auto-publisher
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
        env:
          GH_AUTH_SECRET: ${{ secrets.GH_AUTH_SECRET }}
          GH_AUTH_SECRET2: ${{ secrets.GH_AUTH_SECRET2 }}
          GH_TEST: test
      - run: pwd
      - run: npm i
      - run: export GH_AUTH_SECRET= ${{ secrets.GH_AUTH_SECRET }}
      - run: export GH_AUTH_SECRET2= ${{ secrets.GH_AUTH_SECRET2 }}
      - run: export GH_TEST= test2
      - run: node ./publisher.js
