name: auto-publisher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
        env:
          GH_AUTH_SECRET: ${{ secrets.GH_AUTH_SECRET }}
      - run: cd auto-publisher
      - run: npm i && node publisher.js
