name: auto-publisher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
      - run: pwd
      - run: npm i
      - run: GH_AUTH_SECRET=${{ secrets.GH_AUTH_SECRET }} node ./publisher.js
