name: build-and-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Build project
        run: npm i && npm run build

      - name: Upload COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
          args: delete -r -f / && upload -r ./public/ /
          secret_id: ${{ secrets.COS_SECRET_ID }}
          secret_key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          region: ${{ secrets.COS_REGION }}

      - name: Flush CDN
        uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
        env:
          SECRET_ID: ${{ secrets.CDN_SECRET_ID}}
          SECRET_KEY: ${{ secrets.CDN_SECRET_KEY }}
          PATHS: "https://www.yukapril.com/"
          FLUSH_TYPE: "flush" # optional
